sudo: false
language: ruby
rvm:
  - 2.5
  - 2.6
env:
  global:
    - CC_TEST_REPORTER_ID=6163381913794d34d745b65d61b589c603cda50fb74c94a54ab0c6305c249bc3
before_install:
  - gem install bundler -v 1.16.2
  - docker-compose -f docker/docker-compose.yml up -d
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
