version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '6000:6000'
    command: -jar DynamoDBLocal.jar -dbPath /var/lib/dynamodb -port 6000
    volumes:
      - /tmp:/var/lib/dynamodb
  minio:
    image: minio/minio
    ports:
      - '6001:9000'
    environment:
      MINIO_ACCESS_KEY: dummy
      MINIO_SECRET_KEY: dummy_secret
    command: server /data
