version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    command: -jar DynamoDBLocal.jar -dbPath /var/lib/dynamodb
    volumes:
      - /tmp:/var/lib/dynamodb
